### PR TITLE
3377 checkmapping

### LINKED ISSUE #3377: The ''delete property'' feature is failing
Delete property feature is failing, and throws an error message.
- Select a template 
- Delete any property 
- The property first disappears 
- Click ''Save'' 
- You get an error message
- Refresh the browser, the deleted property reappears
- Seems to be specific to this instance only

Screenshot 2020-12-16 at 10 00 47

### PR DESCRIPTION
**Pull request by konzz**
fixes #3377

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/search/entitiesIndex.js [hunk 1]
```diff
@@ -170,13 +170,16 @@ const equalPropMapping = (mapA, mapB) => {
...
+  const sameProps =
+    Object.keys(mapA.properties).length === Object.keys(mapB.properties).length &&
+    Object.keys(mapA.properties).reduce(
+      (result, propKey) =>
+        result &&
+        mapB.properties[propKey] &&
+        mapA.properties[propKey].type === mapB.properties[propKey].type,
+      true
+    );
+  return sameProps;
```
Comment (mfacar) [inline app/api/search/entitiesIndex.js:182]: @konzz please could you do an inline variable for this?

**Review by mfacar — COMMENTED** [review]
@konzz, LGTM! I just left a comment for an inline variable

File: app/api/search/entitiesIndex.js (hunk 1 above)
Comment (konzz) [reply app/api/search/entitiesIndex.js]: fixed
