### PR TITLE
Fixed daterange filters

### LINKED ISSUE #2715: Filtering by daterange or multidaterange fields throws an error

### PR DESCRIPTION
**Pull request by konzz**
fixes #2715 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/search/metadataAggregations.js [hunk 1]
```diff
@@ -140,7 +140,10 @@ const propertyToAggregation = (property, dictionaries, baseQuery) => {
     match =>
```
Comment (bdittes) [inline app/api/search/metadataAggregations.js]: This is such a massive hack and this PR is making it worse - can you at least e.g. ?

// TODO: re-build filter instead of relying on internal structure

**Comment by RafaPolit** [comment]
LGTM.

This is critical, It's working, I agree that the structure 'hack' does not look good, let's try and fix it soon.  But I am merging this so that the current filters do not break the app.
