### PR TITLE
Files to updatelogs migration

### LINKED ISSUE #2779: TypeError: Cannot read property 'template' of null
Sync between public and private instance is not working anymore.

# systemctl status uwazi.service
● uwazi.service - uwazi backend service for your-instance
   Loaded: error (Reason: Invalid argument)
   Active: active (running) since Thu 2020-02-06 23:59:06 EST; 1 weeks 5 days ago
 Main PID: 6196 (node)
   CGroup: /system.slice/uwazi.service
           ├─6196 node /usr/local/bin/yarn run-production
           └─6208 node server.js

Feb 19 15:56:40 host3.ABC.org yarn[6196]: at Object.template [as shouldSync] (/home/ABC/public_html/ABCD/uwazi/app/api/sync/syncConfig.js:195:53)
Feb 19 15:56:40 host3.ABC.org yarn[6196]: at anonymous
Feb 19 15:56:45 host3.ABC.org yarn[6196]: 2020-02-19T20:56:45.499Z [localhost]
Feb 19 15:56:45 host3.ABC.org yarn[6196]: TypeError: Cannot read property 'template' of null
Feb 19 15:56:45 host3.ABC.org yarn[6196]: at Object.template [as shouldSync] (/home/ABC/public_html/ABCD/uwazi/app/api/sync/syncConfig.js:195:53)
Feb 19 15:56:45 host3.ABC.org yarn[6196]: at anonymous
Feb 19 15:56:50 host3.ABC.org yarn[6196]: 2020-02-19T20:56:50.532Z [localhost]
Feb 19 15:56:50 host3.ABC.org yarn[6196]: TypeError: Cannot read property 'template' of null
Feb 19 15:56:50 host3.ABC.org yarn[6196]: at Object.template [as shouldSync] (/home/ABC/public_html/ABCD/uwazi/app/api/sync/syncConfig.js:195:53)
Feb 19 15:56:50 host3.ABC.org yarn[6196]: at anonymous

&

# systemctl status uwazi2.service
● uwazi2.service - uwazi backend service for instance2
   Loaded: loaded (/etc/systemd/system/uwazi2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-02-03 15:37:40 EST; 2 weeks 2 days ago
 Main PID: 32580 (node)
   CGroup: /system.slice/uwazi2.service
           └─32580 /usr/local/bin/node server.js

Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead
Feb 06 23:58:25 host3.ABC.org node[32580]: MarkdownLink is deprecated, use <Link to="url"></Link> instead

Error Log: /uwazi/log/error.log

[localhost] 
TypeError: Cannot read property 'template' of null
    at Object.template [as shouldSync] (/home/ABCpublic_html/ABCD/uwazi/app/api/sync/syncConfig.js:195:53)
    at anonymous

### PR DESCRIPTION
**Pull request by daneryl**
this updates the updatelogs collection to include all files logs that were created on migration 21, this migrations do NOT need a reindex.

@RafaPolit this also includes now migration 23, and a errorLog to try to track an error happening and creating updatelogs without mongoId, we are assuming here that when this happens the document does not get created, all this migration does is remove those bugged updatelogs for the sync to coninue working.

fixes #2779

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/odm/model.ts [hunk 1]
```diff
@@ -32,8 +31,16 @@ class UpdateLogHelper {
   }
 
   upsertLogOne(doc: mongoose.Document, next: (err?: mongoose.NativeError) => void) {
+    // temporary prevent creating updateLogs without mongoid, log error
+    if (!doc._id) {
+      errorLog.error(
+        `ERROR, Update Log received a doc without _id:\n ${JSON.stringify(doc, null, ' ')}`
```
Comment (RafaPolit) [inline app/api/odm/model.ts]: Should we include here the collection name as well, to help us debug from where is this coming?  Or are we sure they are always entities?

**Comment by RafaPolit** [comment]
Other than that minor comment, LGMT.  Migrations work on randomly tested instances locally.

File: app/api/odm/model.ts (hunk 1 above)
Comment (daneryl) [reply app/api/odm/model.ts]: @RafaPolit we do not know what doc is in that case, all updatelogs without mongoId i have found are entities.
