### PR TITLE
Fixed display of nested values in table view

### LINKED ISSUE #4161: Display of values from nested thesaurus when selected using a Multi-select property (3 pts)
When a template has a multi-select property and an option in a nested thesaurus is selected, the value of the option does not display when the view is on table view it rather shows "Object Object".

See below a screenshot :

Capture d’écran 2022-01-21 à 11 55 49

### LINKED ISSUE #4226: Inherited properties are not displayed in table view
dixit

### PR DESCRIPTION
**Pull request by grafitto**
fixes #4161 
fixes #4226 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [x] Smoke test the functionality described in the issue
- [x] Test for side effects
- [x] UI responsiveness
- [x] Cross browser testing
- [x] Code review

### CODE REVIEW

File: app/react/Library/components/TableCell.tsx [hunk 1]
```diff
@@ -4,15 +4,19 @@ import { I18NLink } from 'app/I18N';
...
 import MarkdownViewer from 'app/Markdown';
+import { showByType } from 'app/Metadata/components/Metadata';
 
 export interface TableCellProps {
   content?: FormattedMetadataValue;
   zoomLevel: number;
 }
 
-export interface FormattedMetadataValue extends PropertySchema {
+export type FormattedMetadataValue = Omit<PropertySchema, 'type'> & {
```
Comment (Zasa-san) [inline app/react/Library/components/TableCell.tsx:14]: Can you please export `FormattedMetadataValue` & `TabelCellProps` at the end of the file?

**Review by Zasa-san — CHANGES_REQUESTED** [review]
LGTM!

File: app/react/Library/components/TableCell.tsx (hunk 1 above)
Comment (grafitto) [reply app/react/Library/components/TableCell.tsx]: Done
