### PR TITLE
sync not returned anymore by default on settings

### LINKED ISSUE #2540: Instances with sync configured, fail to save settings from the UI
Some sync instances reporting problems with synced instances.

### PR DESCRIPTION
**Pull request by daneryl**
fixes #2540

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/sync/syncWorker.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ export default {
   },
 
   async start(interval) {
-    const { sync } = await settings.get();
+    const { sync } = await settings.get(true);
```
Comment (RafaPolit) [inline app/api/sync/syncWorker.js]: Should we start a coding practice to pass semantic objects rather than this standalone values?

For example, if this would be: `settings.get({ selectPrivateValues: true})`, I believe this would much more readable.

I also think it helps passing this 'config' arguments in a much better way, if you latter on need a new param, you just add the key, instead of needing to change the number of arguments on the function (but this is kind of secondary to the main legibility point).

What do you guys think? cc @daneryl @konzz @gabriel-piles @fnocetti 
Maybe this is worth discussing in the tech call?

Comment (daneryl) [reply app/api/sync/syncWorker.js]: @RafaPolit i agree, we use the string notation '+field' but we should use maybe the object notation also supported,
{ field: 1, noReturnField: 0}, as for other scenarios, we can rely on Typescript to know what things are.

Comment (daneryl) [reply app/api/sync/syncWorker.js]: @RafaPolit ill change it to be more readable.

Comment (daneryl) [reply app/api/sync/syncWorker.js]: @RafaPolit i did change the settings get method to be more standard, now you actually have to ask for properties that are marked as select: false, explicitly.

**Comment by fnocetti** [comment]
@daneryl I'm still experiencing the issue as described in #2540.
Steps to reproduce:

1. Configure data sync in the instance.
2. Log in as an administrator
3. Try to edit any setting (i.e. The collection name)

Result: "ValidationError: "sync" is not allowed"

**Comment by daneryl** [comment]
@fnocetti im not able to replicate, can you guide me on how to get the validation error ?
