### PR TITLE
Proper handling of errors on server side rendering

### LINKED ISSUE #2841: Forcing the query limit to more than the hardcoded 10.000k crashes the request
Forcing a query limit form 60 to ie. 60000 ~~leaves the server unresponsive.~~ (crashes the request)

### PR DESCRIPTION
**Pull request by txau**
fixes #2841

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [x] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/ServerRouter.js [hunk 1]
```diff
@@ -225,7 +230,9 @@ function handleRoute(res, renderProps, req) {
         true
       );
     })
-    .catch(e => handleError(e, { req }));
+    .catch(e => {
+      respondError(res, e);
```
Comment (RafaPolit) [inline app/react/ServerRouter.js:234]: This makes the entire function return a resolved promise with `undefined`.  The previous implementation actually returned the result of handleError.  Please make sure this is a desired effect on the function to not have a return.

Comment (daneryl) [reply app/react/ServerRouter.js:234]: @RafaPolit @txau, this is ok no one is actually expecting any return here.
