### PR TITLE
2838 migrate geolocation to numbers

### LINKED ISSUE #2838: some instances crash when map receives lat,lon as strings
we should prepare a migration to repair old instances with lat,lon as strings, as with the new validation this can not happen anymore, or we should allow our map component to accept strings also.

### PR DESCRIPTION
**Pull request by fnocetti**
fixes #2838 

This pr also adds support for reporting to the activity log from the migrations.

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/migrations/migrations/25-sanitize-string-geolocations/index.js [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+  if (!Array.isArray(property) || !property.length) {
+    return property;
+  }
+
+  const value = { ...property[0].value };
+
+  // eslint-disable-next-line no-new-wrappers
+  const lat = new Number(value.lat).valueOf();
+  // eslint-disable-next-line no-new-wrappers
+  const lon = new Number(value.lon).valueOf();
```
Comment (daneryl) [inline app/api/migrations/migrations/25-sanitize-string-geolocations/index.js:17]: @fnocetti there should be no need of eslint disable here, it should work if you remove the "new" operator i think ?

File: app/api/migrations/migrations/25-sanitize-string-geolocations/specs/fixtures.js [hunk 2]
```diff
@@ -0,0 +1,101 @@
+/** @format */
```
Comment (daneryl) [inline app/api/migrations/migrations/25-sanitize-string-geolocations/specs/fixtures.js:1]: @fnocetti format not needed anymore.

File: app/api/activitylog/migrationsParser.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+
+    const semantic = {
+      beautified: true,
+      action: methods.migrate,
+      name: `${title} (${sharedId})`,
+      extra: 'Must fix manually',
+      description: `[${migrationName}] Error parsing property ${propertyName} in`,
+    };
+
+    return semantic;
```
[the remark this answers is not in the document]
Comment (fnocetti) [reply app/api/activitylog/migrationsParser.js:15]: Fixing it!

File: app/api/activitylog/migrationsParser.js [hunk 4]
```diff
@@ -0,0 +1,17 @@
+import { methods } from './helpers';
+
+export default {
```
[the remark this answers is not in the document]
Comment (fnocetti) [reply app/api/activitylog/migrationsParser.js:3]: Got it. I'll fix it and try to put a eslint rule. If this is something we want to avoid, it makes total sense to have the rule in place to me.

File: app/api/migrations/migrations/25-sanitize-string-geolocations/specs/fixtures.js (hunk 2 above)
Comment (fnocetti) [reply app/api/migrations/migrations/25-sanitize-string-geolocations/specs/fixtures.js:1]: Second time it happens to me when cloning a file for reference [facepalm], I'm sorry. I'll take care of it.
Btw, might it be a good idea to remove those comments from every other file?

**Comment by fnocetti** [comment]
@daneryl please check again. I left out the eslint rule so we can talk about it in the tech meeting.

**Comment by daneryl** [comment]
LGTM
