### PR TITLE
3311 schema fix

### LINKED ISSUE #3311: Check the objectIdSchema type, it is casgting 'unknown | undefined'
The objectIdSchema imported everywhere where _id is defined in types / validations, is casting a:
```
string | { [k: string]: unknown | undefined; }
```
type, which is probably not correct.  We should look into this.

### PR DESCRIPTION
**Pull request by RafaPolit**
fixes #3311

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/attachments/attachments.ts [hunk 1]
```diff
@@ -34,12 +34,16 @@ export default {
       _id: { $ne: entity._id },
     });
 
-    const attachmentToDelete = (entity.attachments || []).find(a => a._id.equals(attachmentId));
+    const attachmentToDelete = (entity.attachments || []).find(
+      a => a._id && a._id.toString() === attachmentId.toString()
```
Comment (RafaPolit) [inline app/api/attachments/attachments.ts:38]: @daneryl I'd like to understand why `a._id?.toString()` is not a better approach. As I understand it, it is, precisely, a shortcand to avoid these extra controls.  Also, it will return `undefined` if any of the checks fail, which is the same (mostly) as doing this booleans which would return false.  

So, using this in filters and other boolean comparators seems like the way to go.

Thanks for any feedback.

File: app/api/templates/specs/utils.spec.ts [hunk 2]
```diff
@@ -13,9 +13,9 @@ describe('templates utils', () => {
       it('should sanitize the labels and append the type', async () => {
         await settings.save({});
         const result = await generateNamesAndIds([
-          { label: ' my prop ', type: 'text' },
-          { label: 'my^foreïgn$próp"', type: 'text' },
-          { label: ' my prop ', type: 'geolocation' },
+          { label: ' my prop ', name: '', type: 'text' },
```
Comment (RafaPolit) [inline app/api/templates/specs/utils.spec.ts:16]: Refactor into conforming property function

File: app/react/Review/components/OneUpEntityViewer.tsx [hunk 3]
```diff
@@ -185,7 +184,7 @@ export class OneUpEntityViewerBase extends Component<
                           showType={false}
                           showSubset={this.nonMlProps()}
                         />
-                        <FileList files={entity.documentsdocuments} entity={entity} />
+                        <FileList files={entity.documents} entity={entity} />
```
Comment (RafaPolit) [inline app/react/Review/components/OneUpEntityViewer.tsx:187]: Here, I had to just assume that `documentsdocuments` is a typo.  No idea if that ever worked.  We have NOTHING in the entire system that assigns a `documentsdocuemnts` property. Still, I cannot test this properly, so it is just an assumption.

Comment (daneryl) [reply app/react/Review/components/OneUpEntityViewer.tsx:187]: this is 100% a typo
